require "grounip.options"
require "grounip.keymaps"
require "grounip.plugins"
require "grounip.colorscheme"
require "grounip.cmp"
require "grounip.lsp"
require "grounip.telescope"
require "grounip.treesitter"
